### ISSUE TITLE
how to use in module context?

### ISSUE THREAD

**Issue by augustblack** [webtiming/timingsrc#22]
Hi,

This project looks really amazing.

Is there perhaps an npm package somewhere that could be used?

This npm pkg says it was published last over 2 years ago?  

https://www.npmjs.com/package/webtiming-timingsrc

Is that the same thing (there is another timingsrc pkg out there) and the most recent?

**Comment by ingararntzen** [comment]
Hi - and thanks.

This npm package has been put out by someone else, so I don't know. I notice that the build instructions refer to v3, but the referenced documentation concerns v2 - so that's not promising.

**Comment by augustblack** [comment]
okay, I see that after I build the project with `python3 compile.py v3` I can then include it in a module based npm project with `npm install --save ../path/to/timingsrc`

It would be great to just adjust the package.json to upload a package to npm registry.

I'd be happy to work on that if you want

**Comment by ingararntzen** [comment]
Thanks, that would be great!

I'm not working much with node myself, so that would be really helpful.

No code modification required?
