### ISSUE TITLE
Is it possible to use with https://github.com/chrisguttandin/timing-provider-server

### ISSUE THREAD

**Issue by augustblack** [webtiming/timingsrc#23]
Hi,

Again, very cool project here!

How does one create a timing provider?

there seems to be no `TIMINGSRC.TimingProvider('ws://localhost:4567') ` ?
 
And, is it possible to use this time provider server (over websockets without webrtc?):  
https://github.com/chrisguttandin/timing-provider-server

How would one go about that?

**Comment by ingararntzen** [comment]
There is no timing provider implementation as part of the timingsrc library.

I'd recommend using the Motion Corporation [timing provider](https://timingsrc.readthedocs.io/en/latest/demoes/demo_timingprovider.html)

Otherwise, check with @chrisguttandin for the one you mention.

**Comment by augustblack** [comment]
thanks for your response!  and, for this cool project.

Will there be a TimingProvider in the future?

I understand if not, but it would be really great if so.

**Comment by ingararntzen** [comment]
It could be, but for the time being, I don't have time/funding for that ;)

**Comment by augustblack** [comment]
thanks for the consideration.
