### ISSUE TITLE
multi-device sequencer example doesn't work

### ISSUE THREAD

**Issue by augustblack** [webtiming/timingsrc#24]
Hi,

Is it just me or is this demo not functional?

https://webtiming.github.io/timingsrc/doc/online_sequencer.html

also, it seems like the docu at the bottom seems off too:

```
// Load data
var r = s.request();  // <--- IS THIS V2 only?
Object.keys(data).forEach(function (key) {
	r.addCue(key, new TIMINGSRC.Interval(data[key].start, data[key].end));
});
r.submit();
```

**Comment by ingararntzen** [comment]
Hi.

It works on my end. Please note what the problem might be.

`var r = s.request();  // <--- IS THIS V2 only?`

Yes, v2 only. Please check out the (unannounced) v3 doc if you are using the v3 bundle.

[https://timingsrc.readthedocs.io](https://timingsrc.readthedocs.io)

and the corresponding single-device sequencer 
[demo](https://timingsrc.readthedocs.io/en/latest/demoes/demo_point_sequencer.html)  or the media sync [demo](https://timingsrc.readthedocs.io/en/latest/demoes/demo_mediasync.html) for multi-device bindings

**Comment by augustblack** [comment]
something must have been off yesterday.  I'm on a spotty low-bandwidth connection in Sri Lanka.

Seems to work today.

Thanks for the links to the v3 docs.
