### ISSUE TITLE
Correct parameters of "off" method for unsubscribing event listeners

### ISSUE THREAD

**Issue by LubomirFedor** [webtiming/timingsrc#29]
[In the documentation for v3](https://timingsrc.readthedocs.io/en/latest/api/api_events.html#EventProviderInterface.off), the signature of `off()` method is like this:
```javascript
 EventProviderInterface.off(name, subscription)
```
with the name parameter being the name of the event and the subscription is the subscription handle from `on()`

However, in [this v3 implementation](https://webtiming.github.io/timingsrc/lib/timingsrc-esm-v3.js) (used for instance in [this demo](https://timingsrc.readthedocs.io/en/latest/demoes/demo_timingobject.html)), there is a function 
`function eventifyPrototype(_prototype)` and within in the following code:
```javascript
/*
OFF
- used by subscriber
Un-register a handler from a specfic event type
*/
function off(sub) {
	return eventifyGetEvent(this, sub.name).unsubscribe(sub);
}
```
And indeed, if I call `off()` like this:
```javascript
myTimingObject.off("timeupdate",mySubscription);
```
an error is thrown from the above mentioned function. However, if I omit the name of the event and use it like this:
```javascript
myTimingObject.off(mySubscription);
```
everything seems to be working alright. So either the documentation or the implementation is wrong.

**Comment by ingararntzen** [comment]
Hi @LubomirFedor. Thanks for this!

The documentation was incorrect. It should be fixed now.
