### ISSUE TITLE
MediaSync doesn't work

### ISSUE THREAD

**Issue by alijaya** [webtiming/timingsrc#7]
It gives Error of "handler already registered", using the MCorp version works

**Comment by ingararntzen** [comment]
Hi @alijaya 

Thanks!

Yes, the version in the timingsrc repository is actually deprecated, so keep using MCorp version, which is currently the maintained version.

I had already removed references to it in the docs I think, but not yet removed the code. Sorry about that.

Will remove obsolete mediasync code from repository shortly, so as to avoid further confusion.  

Best, Ingar

**Comment by alijaya** [comment]
oh ok then, thanks for the clarification :D

**Comment by Laurian** [comment]
MCorp version? where is the repo for that one?

**Comment by Snarkdoof** [comment]
You can find it at https://mcorp.no/lib/mediasync.js

Best
N

On Mon, 1 Apr 2019 at 18:57, Laurian Gridinoc <notifications@github.com<mailto:notifications@github.com>> wrote:

MCorp version? where is the repo for that one?
