### ISSUE TITLE
MCorp Issue

### ISSUE THREAD

**Issue by alijaya** [webtiming/timingsrc#8]
I'm not sure if I can post here about the issue with MCorp. But today, 19 March 2019, at 15:40 (UTC+1), the server is not responding. The sync is not working, even the example in here: http://webtiming.github.io/timingsrc/doc/online_timingobject.html

what's the problem exactly?

**Comment by alijaya** [comment]
I'm not sure if it's only me or I'm doing something wrong :-?... it's working now

**Comment by Snarkdoof** [comment]
Sorry for the inconvenience, we had a minor outage. It's up and running now though.

N

On Tue, 19 Mar 2019 at 15:41, Ali Jaya Meilio <notifications@github.com<mailto:notifications@github.com>> wrote:

I'm not sure if I can post here about the issue with MCorp. But today, 19 March 2019, at 15:40 (UTC+1), the server is not responding. The sync is not working, even the example in here: http://webtiming.github.io/timingsrc/doc/online_timingobject.html

what's the problem exactly?

**Comment by alijaya** [comment]
Ah it's really from the server? How can we see the server status btw?

**Comment by Snarkdoof** [comment]
We are working on a new dashboard which will provide real time info about
all your apps. The console of the browser also prints if connections are
lost to the server. That's normally not issues, but power saving, suspended
threads or network changes, but it will show if you can reach it at least.

N
